version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "@biomejs/*"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "@playwright/*"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "@types/*"
        update-types:
          - "version-update:semver-patch"
